version: "3.9"
services:
  # web:
  #   build: .
  #   ports:
  #     - "8000:5000"
  ui:
    image: cypress/base:latest
    # if targeting a specific node version, use e.g.
    # image: cypress/base:14